### ISSUE TITLE
Switch to MIT

### ISSUE THREAD

**Issue by MatthewRock** [k-stz/cl-ptrace#3]
One problem with this library is that you can't really use it - no license means it's All Rights Reserved.

Second problem is that to incorporate the library into quicklisp, it must 

(a) Have "Author" field in ASD file(done)
(b) Have "License" field in ASD file with open source license(not done)
(c) Compile on at least two compilers(unknown).

I would appreciate if you updated your library to fit these requirements. If you have any questions, please let me know.

**Comment by k-stz** [comment]
Hello,

thank you for pointing that out! 

I've solved the issue (b) by adding a license. As for (c) the compilation on multiple compilers, I have to put that on hold because the program as it stands should only work on 64bit CPUs because of some hardcoding, and perhaps other quirks.

Before that functionality is not available, I think, making it available for quicklisp (if that was the prime intent of having it work on multiple compilers) wouldn't be an acceptable solution, as it would compile but not work properly. 

Sadly, I don't have the means to test and implement that feature yet.

cheers

**Comment by MatthewRock** [comment]
With the license now added I might help you with the code if I find some spare time.

Quicklisp requires a compilation to succeed on at least two compilers. One of the more popular ones are probably SBCL, ECL, CCL and commercial ones. Allowing this to compile on two 64-bit compilers would be acceptable, I hope.

The License problem is resolved, so I'm closing the issue. I hope we will find way to make it build on as many compilers as we can.
